
services:
  web:
    image: nginx:latest
    ports:
      - '8081:80'
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html
  
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
  django:
    container_name: simple_lms
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"
  postgres:
    container_name: simple_db
    image: postgres:latest
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    